# Generated by Django 4.2.3 on 2023-08-01 06:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('crawling_status', models.IntegerField(default=0)),
                ('target_product', models.CharField(max_length=100, unique=True)),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='author_project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_1st', models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 1, 6, 9, 41, 655609, tzinfo=datetime.timezone.utc))),
                ('date_2nd', models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 1, 6, 9, 41, 655609, tzinfo=datetime.timezone.utc))),
                ('brand_add', models.TextField(blank=True, null=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
