# Generated by Django 4.2.3 on 2023-08-01 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_setting',
            name='date_1st',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 1, 6, 10, 1, 707267, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project_setting',
            name='date_2nd',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 1, 6, 10, 1, 707267, tzinfo=datetime.timezone.utc)),
        ),
    ]
