# Generated by Django 4.2.3 on 2023-07-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='crawling_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='target_product',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
