# Generated by Django 4.2.3 on 2023-08-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_setting_date_1st_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_setting',
            name='date_1st',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project_setting',
            name='date_2nd',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
