# Generated by Django 4.2.3 on 2023-08-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_setting_date_1st_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_setting',
            name='mall_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
